spring:
  datasource: # 数据库链接
    url: jdbc:mysql://192.168.200.247:3306/kettle-db?serverTimezone=UTC&useSSL=false
    username: root
    password: songcw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true # sql打印
    database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    open-in-view: false # false关闭懒加载
  redis: # redis缓存配置
    host: 192.168.200.247
    port: 6379
    password: qazwsx
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
logging: # 日志记录
  level:
    root: info
    org.kettle.scheduler: info
  file: /logs/${spring.application.name}.log
