spring:
  datasource: # 数据库链接
    url: jdbc:mysql://10.51.13.133:3306/bi_scheduler?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: wuhe
    password: Xhwl_Wh@2019
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 18000000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    show-sql: true # sql打印
    database-platform: org.hibernate.dialect.MySQLDialect # 数据库方言
    open-in-view: false # false关闭懒加载
logging: # 日志记录
  level:
    root: info
    org.kettle.scheduler: info
  file: /logs/${spring.application.name}.log
